import Head from "next/head";
import Image from "next/image";

import styles from "../styles/Home.module.css";

import BWLogo from "../img/bildungswerk_logo.png";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bildungswerk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.contentContainer}>
          <div className={styles.logoContainer}>
            <Image src={BWLogo} alt="Bildungswerk Logo" priority />
          </div>
          <p className={styles.subHead}>
            <strong>„Mernissi-de Gouges“</strong> – interreligiöses
            humanistisches Bil- dungswerk für Freiheit, Demokratie und
            Rechtsstaatlichkeit gUG (haftungsbeschränkt)
          </p>

          <p className={styles.downloadLink}>
            Diese Seite befindet sich gerade im Aufbau. Wenn Sie möchten, laden
            Sie sich unsere{" "}
            <strong>
              <a href="https://drive.google.com/uc?export=download&id=1EgSqfm7BDJw3woS5T3iE8BxzpEat7c73">
                Kurzdarstellung
              </a>
            </strong>{" "}
            herunter.
          </p>
        </div>
      </main>
      <footer className={styles.footer}>
        <div className={styles.contact}>
          <p>
            <strong>Mernissi-de Gouges Bildungswerk gUG</strong>
          </p>
          <p>Ottostraße 16, D - 10555 Berlin </p>
          <p>
            <a href="mailto:post@mdg-bildungswerk.de">
              post@mdg-bildungswerk.de
            </a>
          </p>
        </div>
        <div className={styles.person}>
          <p>Geschäftsführerin</p>
          <p>Seyran Ateş</p>
        </div>
        <div></div>
      </footer>
    </div>
  );
}
